coverage:
  status:
    project:
      default:
        target: 90%

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: true
  require_head: true

flags:
  monolith:
    paths:
      - coverage/packages/monolith
  nest-auth:
    paths:
      - coverage/packages/nest-auth
