name: CI
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: nx format:check
      - run: nx affected -t lint --parallel=3
      - run: nx run-many -t test --parallel=3 --configuration=ci
      - run: nx affected -t build --parallel=3
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage
          retention-days: 1

  coverage_monolith:
    needs: main
    name: coverage:monolith
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: coverage
          path: coverage
      - uses: codecov/codecov-action@v3
        with:
          flags: monolith
          directory: coverage/packages/monolith
